# Generated by Django 5.2.15 on 2026-06-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo de la Empresa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Promoción')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la Promoción')),
                ('start_date', models.DateField(blank=True, db_index=True, help_text='Fecha en formato AAAA-MM-DD', null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fecha en formato AAAA-MM-DD', null=True, verbose_name='Fecha de Fin')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Requisitos para la Promoción')),
                ('access_link', models.URLField(blank=True, null=True, verbose_name='Enlace de Acceso a la Promoción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotion_images/', verbose_name='Imagen de la Promoción')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='states.city', verbose_name='Ciudad')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='promotions.company', verbose_name='Empresa')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='states.municipality', verbose_name='Municipio')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='states.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotion_images/', verbose_name='Imagen de la Promoción')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promotions.promotion', verbose_name='Promoción')),
            ],
            options={
                'verbose_name': 'Imagen de Promoción',
                'verbose_name_plural': 'Imágenes de Promociones',
            },
        ),
    ]
