# Generated by Django 5.2.15 on 2026-06-20 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Estado al que pertenece la empresa. Vacío = alcance nacional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='states.state', verbose_name='Estado'),
        ),
    ]
