# Generated by Django 5.2.15 on 2026-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_estatal_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
