# Generated by Django 5.2.15 on 2026-06-20 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_event_headquarters_event_organizing_institution_and_more'),
        ('promotions', '0002_company_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_record', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Expediente Digital',
                'verbose_name_plural': 'Expedientes Digitales',
            },
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='Búsqueda')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='records.digitalrecord', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Búsqueda reciente',
                'verbose_name_plural': 'Búsquedas recientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='records/docs/', verbose_name='Archivo')),
                ('document_type', models.CharField(blank=True, help_text='Ej. Identificación, Comprobante de estudios.', max_length=80, verbose_name='Tipo de documento')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10, verbose_name='Estatus')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.digitalrecord', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Documento del expediente',
                'verbose_name_plural': 'Documentos del expediente',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Guardado')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='programs.event', verbose_name='Evento')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='programs.program', verbose_name='Programa')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='promotions.promotion', verbose_name='Promoción')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='records.digitalrecord', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Elemento guardado',
                'verbose_name_plural': 'Elementos guardados',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('program__isnull', False), ('promotion__isnull', True)), models.Q(('event__isnull', False), ('program__isnull', True), ('promotion__isnull', True)), models.Q(('event__isnull', True), ('program__isnull', True), ('promotion__isnull', False)), _connector='OR'), name='saveditem_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('program__isnull', False)), fields=('record', 'program'), name='uniq_saved_program'), models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('record', 'event'), name='uniq_saved_event'), models.UniqueConstraint(condition=models.Q(('promotion__isnull', False)), fields=('record', 'promotion'), name='uniq_saved_promotion')],
            },
        ),
    ]
