# Generated by Django 5.2.15 on 2026-06-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Evento')),
                ('start_date', models.DateField(blank=True, db_index=True, help_text='Fecha en formato AAAA-MM-DD', null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fecha en formato AAAA-MM-DD', null=True, verbose_name='Fecha de Fin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/', verbose_name='Poster del Evento')),
                ('description', models.TextField(verbose_name='Descripción del Evento')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='states.city', verbose_name='Ciudad')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='states.municipality', verbose_name='Municipio')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='states.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Programa')),
                ('start_date', models.DateField(blank=True, db_index=True, help_text='Fecha en formato AAAA-MM-DD', null=True, verbose_name='Fecha de Inicio')),
                ('age_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Mínima')),
                ('age_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Máxima')),
                ('end_date', models.DateField(blank=True, help_text='Fecha en formato AAAA-MM-DD', null=True, verbose_name='Fecha de Fin')),
                ('access_link', models.URLField(blank=True, null=True, verbose_name='Enlace de Acceso al Programa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/', verbose_name='Poster del Programa')),
                ('description', models.TextField(verbose_name='Descripción del Programa')),
                ('cities', models.ManyToManyField(blank=True, related_name='programs', to='states.city', verbose_name='Ciudades')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='states.municipality', verbose_name='Municipio')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='states.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_images/', verbose_name='Imagen de Documentación')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='programs.event', verbose_name='Evento')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='programs.program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Requisito')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='programs.event', verbose_name='Evento')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='programs.program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
    ]
