# Generated by Django 5.2.15 on 2026-06-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='headquarters',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sede del Evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizing_institution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución Organizadora'),
        ),
        migrations.AddField(
            model_name='program',
            name='organizing_institution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución Organizadora'),
        ),
    ]
