# Generated by Django 5.2.15 on 2026-06-19 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='age_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad máxima'),
        ),
        migrations.AddField(
            model_name='test',
            name='age_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad mínima'),
        ),
        migrations.AddField(
            model_name='test',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='states.city', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='test',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='states.municipality', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='test',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='states.state', verbose_name='Estado'),
        ),
    ]
