# Generated by Django 5.2.15 on 2026-06-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_age_max_test_age_min_test_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Opción de Pregunta', 'verbose_name_plural': 'Opciones de Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test/Cuestionario', 'verbose_name_plural': 'Tests/Cuestionarios'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='¿Correcta?'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Texto de la opción'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TXT', 'Texto Libre'), ('MC', 'Opción Múltiple')], default='TXT', max_length=3, verbose_name='Tipo de pregunta'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
    ]
